// Auth
// export type LOGIN_START = "LOGIN_START";
// export type LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export type LOGIN_ERROR = "LOGIN_ERROR";
// export type LOGIN_RESET = "LOGIN_RESET";

export enum SetupType {
  // * Auth
  LOGIN_START = "LOGIN_START",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_RESET = "LOGIN_RESET",

  REGISTER_START = "REGISTER_START",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_RESET = "REGISTER_RESET",

  // * User
  IS_LOGGED_IN_START = "IS_LOGGED_IN_START",
  IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN_SUCCESS",
  IS_LOGGED_IN_RESET = "IS_LOGGED_IN_RESET",

  DELETE_ACCOUNT_START = "DELETE_ACCOUNT_START",
  DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_RESET = "DELETE_ACCOUNT_RESET",

  UPDATE_USER_PASSWORD_START = "UPDATE_USER_PASSWORD_START",
  UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS",
  UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET",

  DELETE_USER_AVATAR_START = "DELETE_USER_AVATAR_START",
  DELETE_USER_AVATAR_SUCCESS = "DELETE_USER_AVATAR_SUCCESS",
  DELETE_USER_AVATAR_RESET = "DELETE_USER_AVATAR_RESET",

  UPLOAD_USER_AVATAR_START = "UPLOAD_USER_AVATAR_START",
  UPLOAD_USER_AVATAR_SUCCESS = "UPLOAD_USER_AVATAR_SUCCESS",
  UPLOAD_USER_AVATAR_RESET = "UPLOAD_USER_AVATAR_RESET",

  LOGOUT_START = "LOGOUT_START",
  LOGOUT_RESET = "LOGOUT_RESET",

  // * Task
  GET_TASK_START = "GET_TASK_START",
  GET_TASK_SUCCESS = "GET_TASK_SUCCESS",
  GET_TASK_RESET = "GET_TASK_RESET",

  GET_TASKS_START = "GET_TASKS_START",
  GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS",
  GET_TASKS_RESET = "GET_TASKS_RESET",

  CREATE_TASK_START = "CREATE_TASK_START",
  CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS",
  CREATE_TASK_RESET = "CREATE_TASK_RESET",

  UPDATE_TASK_START = "UPDATE_TASK_START",
  UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_RESET = "UPDATE_TASK_RESET",

  DELETE_TASK_START = "DELETE_TASK_START",
  DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS",
  DELETE_TASK_RESET = "DELETE_TASK_RESET",

  UPLOAD_TASK_START = "UPLOAD_TASK_START",
  UPLOAD_TASK_SUCCESS = "UPLOAD_TASK_SUCCESS",
  UPLOAD_TASK_RESET = "UPLOAD_TASK_RESET",

  END_TASK_START = "END_TASK_START",
  END_TASK_SUCCESS = "END_TASK_SUCCESS",
  END_TASK_RESET = "END_TASK_RESET",

  // * Group
  GET_GROUP_START = "GET_GROUP_START",
  GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS",
  GET_GROUP_RESET = "GET_GROUP_RESET",

  GET_GROUPS_START = "GET_GROUPS_START",
  GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS",
  GET_GROUPS_RESET = "GET_GROUPS_RESET",

  CREATE_GROUP_START = "CREATE_GROUP_START",
  CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS",
  CREATE_GROUP_RESET = "CREATE_GROUP_RESET",

  UPDATE_GROUP_START = "UPDATE_GROUP_START",
  UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS",
  UPDATE_GROUP_RESET = "UPDATE_GROUP_RESET",

  DELETE_GROUP_START = "DELETE_GROUP_START",
  DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS",
  DELETE_GROUP_RESET = "DELETE_GROUP_RESET",

  LEADER_DO_START = "LEADER_DO_START",
  LEADER_DO_SUCCESS = "LEADER_DO_SUCCESS",
  LEADER_DO_RESET = "LEADER_DO_RESET",

  LEADER_REMOVE_START = "LEADER_REMOVE_START",
  LEADER_REMOVE_SUCCESS = "LEADER_REMOVE_SUCCESS",
  LEADER_REMOVE_RESET = "LEADER_REMOVE_RESET",

  JOIN_GROUP_START = "JOIN_GROUP_START",
  JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS",
  JOIN_GROUP_RESET = "JOIN_GROUP_RESET",

  // * Post
  DELETE_POST_START = "DELETE_POST_START",
  DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS",
  DELETE_POST_RESET = "DELETE_POST_RESET",

  GET_POSTS_START = "GET_POSTS_START",
  GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
  GET_POSTS_RESET = "GET_POSTS_RESET",

  CREATE_POST_START = "CREATE_POST_START",
  CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
  CREATE_POST_RESET = "CREATE_POST_RESET",

  // * Question
  GET_QUESTIONS_START = "GET_QUESTIONS_START",
  GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS",
  GET_QUESTIONS_RESET = "GET_QUESTIONS_RESET",

  CREATE_QUESTION_START = "CREATE_QUESTION_START",
  CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS",
  CREATE_QUESTION_RESET = "CREATE_QUESTION_RESET",

  // * Answer
  CREATE_ANSWER_START = "CREATE_ANSWER_START",
  CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS",
  CREATE_ANSWER_RESET = "CREATE_ANSWER_RESET",

  // * Sub Task
  GET_SUB_TASK_START = "GET_SUB_TASK_START",
  GET_SUB_TASK_SUCCESS = "GET_SUB_TASK_SUCCESS",
  GET_SUB_TASK_RESET = "GET_SUB_TASK_RESET",

  GET_SUB_TASKS_START = "GET_SUB_TASKS_START",
  GET_SUB_TASKS_SUCCESS = "GET_SUB_TASKS_SUCCESS",
  GET_SUB_TASKS_RESET = "GET_SUB_TASKS_RESET",

  CREATE_SUB_TASK_START = "CREATE_SUB_TASK_START",
  CREATE_SUB_TASK_SUCCESS = "CREATE_SUB_TASK_SUCCESS",
  CREATE_SUB_TASK_RESET = "CREATE_SUB_TASK_RESET",

  UPDATE_SUB_TASK_START = "UPDATE_SUB_TASK_START",
  UPDATE_SUB_TASK_SUCCESS = "UPDATE_SUB_TASK_SUCCESS",
  UPDATE_SUB_TASK_RESET = "UPDATE_SUB_TASK_RESET",

  DELETE_SUB_TASK_START = "DELETE_SUB_TASK_START",
  DELETE_SUB_TASK_SUCCESS = "DELETE_SUB_TASK_SUCCESS",
  DELETE_SUB_TASK_RESET = "DELETE_SUB_TASK_RESET",

  UPLOAD_SUB_TASK_START = "UPLOAD_SUB_TASK_START",
  UPLOAD_SUB_TASK_SUCCESS = "UPLOAD_SUB_TASK_SUCCESS",
  UPLOAD_SUB_TASK_RESET = "UPLOAD_SUB_TASK_RESET",

  END_SUB_TASK_START = "END_SUB_TASK_START",
  END_SUB_TASK_SUCCESS = "END_SUB_TASK_SUCCESS",
  END_SUB_TASK_RESET = "END_SUB_TASK_RESET",
}

export const types: SetupType[] = [
  // * Auth
  SetupType.LOGIN_START,
  SetupType.LOGIN_SUCCESS,
  SetupType.LOGIN_RESET,

  // * User
  SetupType.IS_LOGGED_IN_START,
  SetupType.IS_LOGGED_IN_SUCCESS,
  SetupType.IS_LOGGED_IN_RESET,

  SetupType.DELETE_ACCOUNT_START,
  SetupType.DELETE_ACCOUNT_SUCCESS,
  SetupType.DELETE_ACCOUNT_RESET,

  SetupType.UPDATE_USER_PASSWORD_START,
  SetupType.UPDATE_USER_PASSWORD_SUCCESS,
  SetupType.UPDATE_USER_PASSWORD_RESET,

  SetupType.DELETE_USER_AVATAR_START,
  SetupType.DELETE_USER_AVATAR_SUCCESS,
  SetupType.DELETE_USER_AVATAR_RESET,

  SetupType.UPLOAD_USER_AVATAR_START,
  SetupType.UPLOAD_USER_AVATAR_SUCCESS,
  SetupType.UPLOAD_USER_AVATAR_RESET,

  SetupType.LOGOUT_START,
  SetupType.LOGOUT_RESET,

  // * Task
  SetupType.GET_TASK_START,
  SetupType.GET_TASK_SUCCESS,
  SetupType.GET_TASK_RESET,

  SetupType.GET_TASKS_START,
  SetupType.GET_TASKS_SUCCESS,
  SetupType.GET_TASKS_RESET,

  SetupType.CREATE_TASK_START,
  SetupType.CREATE_TASK_SUCCESS,
  SetupType.CREATE_TASK_RESET,

  SetupType.UPDATE_TASK_START,
  SetupType.UPDATE_TASK_SUCCESS,
  SetupType.UPDATE_TASK_RESET,

  SetupType.DELETE_TASK_START,
  SetupType.DELETE_TASK_SUCCESS,
  SetupType.DELETE_TASK_RESET,

  SetupType.UPLOAD_TASK_START,
  SetupType.UPLOAD_TASK_SUCCESS,
  SetupType.UPLOAD_TASK_RESET,

  SetupType.END_TASK_START,
  SetupType.END_TASK_SUCCESS,
  SetupType.END_TASK_RESET,

  // * Group
  SetupType.GET_GROUP_START,
  SetupType.GET_GROUP_SUCCESS,
  SetupType.GET_GROUP_RESET,

  SetupType.GET_GROUPS_START,
  SetupType.GET_GROUPS_SUCCESS,
  SetupType.GET_GROUPS_RESET,

  SetupType.CREATE_GROUP_START,
  SetupType.CREATE_GROUP_SUCCESS,
  SetupType.CREATE_GROUP_RESET,

  SetupType.UPDATE_GROUP_START,
  SetupType.UPDATE_GROUP_SUCCESS,
  SetupType.UPDATE_GROUP_RESET,

  SetupType.DELETE_GROUP_START,
  SetupType.DELETE_GROUP_SUCCESS,
  SetupType.DELETE_GROUP_RESET,

  SetupType.LEADER_DO_START,
  SetupType.LEADER_DO_SUCCESS,
  SetupType.LEADER_DO_RESET,

  SetupType.LEADER_REMOVE_START,
  SetupType.LEADER_REMOVE_SUCCESS,
  SetupType.LEADER_REMOVE_RESET,

  // * Post
  SetupType.DELETE_POST_START,
  SetupType.DELETE_POST_SUCCESS,
  SetupType.DELETE_POST_RESET,

  SetupType.GET_POSTS_START,
  SetupType.GET_POSTS_SUCCESS,
  SetupType.GET_POSTS_RESET,

  SetupType.CREATE_POST_START,
  SetupType.CREATE_POST_SUCCESS,
  SetupType.CREATE_POST_RESET,

  // * Sub Task
  SetupType.GET_SUB_TASK_START,
  SetupType.GET_SUB_TASK_SUCCESS,
  SetupType.GET_SUB_TASK_RESET,

  SetupType.GET_SUB_TASKS_START,
  SetupType.GET_SUB_TASKS_SUCCESS,
  SetupType.GET_SUB_TASKS_RESET,

  SetupType.CREATE_SUB_TASK_START,
  SetupType.CREATE_SUB_TASK_SUCCESS,
  SetupType.CREATE_SUB_TASK_RESET,

  SetupType.UPDATE_SUB_TASK_START,
  SetupType.UPDATE_SUB_TASK_SUCCESS,
  SetupType.UPDATE_SUB_TASK_RESET,

  SetupType.DELETE_SUB_TASK_START,
  SetupType.DELETE_SUB_TASK_SUCCESS,
  SetupType.DELETE_SUB_TASK_RESET,

  SetupType.UPLOAD_SUB_TASK_START,
  SetupType.UPLOAD_SUB_TASK_SUCCESS,
  SetupType.UPLOAD_SUB_TASK_RESET,

  SetupType.END_SUB_TASK_START,
  SetupType.END_SUB_TASK_SUCCESS,
  SetupType.END_SUB_TASK_RESET,
];
